steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://sandy8412: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@github.com/sandy8412/Breaking-bugs.git
      #- tmp
      #- --branch
      #- master
      #- --single-branch
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/cn-project-2-413711/breaking-bugs-registry/dev-nginx:$COMMIT_SHA
      - .
    dir: nginx
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/cn-project-2-413711/breaking-bugs-registry/dev-nginx:$COMMIT_SHA
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - >
        sed -i "s|image:.*|image:
        us-central1-docker.pkg.dev/cn-project-2-413711/breaking-bugs-registry/dev-nginx:$COMMIT_SHA|"
        nginx/manifest_files/deploy.yaml
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        git config --global url.https://sandy8412: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@github.com/sandy8412/Breaking-bugs
        git config --global user.email "santhoshgod@6002gmail.com"
        git config --global user.name "sandy8412"
        git config --global credential.helper cache
        git add .
        git commit -m "Update nginx image tag"
        git fetch origin master
        git checkout master
        #git rebase origin/master
        git push origin master
###
